### ISSUE TITLE
[1.20.1 / Forge] Biome Tag Filter Not Working

### ISSUE THREAD

**Issue by aszecsei** [TheComputerizer/Music-Triggers#213]
I have a number of biome tag-based triggers set up:

```toml
  [[triggers.biome]]
    biome_tag = [ "minecraft:is_beach" ]
    identifier = "category_Beach"
    priority = "1"
  # ... etc
```

However, in game, all biome tag-based triggers are active simultaneously:

![Image](https://github.com/user-attachments/assets/41fc8c0e-f46c-4436-9a96-cdeac6c6cc25)
