### ISSUE TITLE
[1.18.2-5.2-hf] Riding Trigger doesn't work

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#28]
Korporal K. Reep#0531 and Manam#0802 reported that riding trigger crashes the moment they mount a mob. Song block example used:

```toml
[horse]
	[horse.trigger]
		name = "riding"
		priority = "201"
		resource_name = "minecraft:horse;minecraft:donkey;minecraft:mule;minecraft:boat;minecraft:strider"
		identifier = "ride"
```

Crash Report from Korporal K. Reep#0531:

https://pastebin.com/n3NzYJcq
