### ISSUE TITLE
Statistics Trigger still doesn't work in Forge 1.16.5

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheComputerizer/Music-Triggers#39]
Hey so i'm unfortunately not able to get the statistic trigger to work:
```toml
[message1]
    [message1.trigger]
        name = "statistic"
        level = "300"
        priority = "9999"
        identifier = "message1"
        resource_name = "play_one_minute"
```

I added this as an additional visual in the commands file to see if it triggers, it doesn't

```toml
[[command]]
        literal = "say its been 300 ticks triggered from statistic trigger"
        triggers = ["statistic-message1"]
```

I then tried:
```toml
[message1]
    [message1.trigger]
        name = "statistic"
        level = "1"
        priority = "9999"
        identifier = "message1"
        resource_name = "mob_kills"
```

but that didn't work after killing a mob either.
Each time I tested these I made sure to create a new world.
These are the correct statistics names, 

I've tried `resource_name = "mob_kills"` and `resource_name = "minecraft:mob_kills"` and `resource_name = "minecraft.mob_kills"`. I made sure to reload the Music Triggers config through the in game gui before starting a new world.
