### ISSUE TITLE
Crash on 5.3 forge, when riding trigger with resource_name

### ISSUE THREAD

**Issue by DRACTION** [TheComputerizer/Music-Triggers#44]
Still crash on 5.3, without `resource_name` works
```toml
[blue_bird_naruto]
	[blue_bird_naruto.trigger]
		name = "riding"
		resource_name = "minecraft:pig"
		identifier = "pig"
```

https://pastebin.com/y9egknrU

_Originally posted by @DRACTION in https://github.com/TheComputerizer/Music-Triggers/issues/28#issuecomment-1126624775_
