### ISSUE TITLE
play_once = "2" doesn't seem to be working on Forge 1.16.5

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheComputerizer/Music-Triggers#46]
```toml
[deadhaha]
	play_once = "2"
	[deadhaha.trigger]
		name = "dead"
		priority = "9999"
```

This is my death trigger, it keeps repeating.

Forge 1.16.5
