### ISSUE TITLE
[1.18.2-5.4-hf] Riding not triggered

### ISSUE THREAD

**Issue by DRACTION** [TheComputerizer/Music-Triggers#51]
**Describe the bug**
Can't use trigger Riding

**To Reproduce**
1. Write this
```toml
[the_only_thing_they_fear_is_you]
	[the_only_thing_they_fear_is_you.trigger]
		name = "riding"
		identifier = "rid"
```
2. Riding on something
3. Nothing hapenned

![image](https://user-images.githubusercontent.com/50882437/169455394-54af8c82-b0cc-4550-9eb5-8a54fce0da33.png)
